<?php

namespace Devcamp\Bundle\SupporterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SupporterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupporterRepository extends EntityRepository
{
}
